chore(deps): use `cuid2` instead of `cuid`
hexojs/warehouse pull request #147
Opened 2023-02-06 14:05 UTC by yoshinorin

## Why

https://github.com/paralleldrive/cuid has been deprecated and we have to use https://github.com/paralleldrive/cuid2 instead.

## Breaking change?

I assume `warehouse` uses `cuid` to generate post id. So, all of the post ids in `db.json` will be changed if we merge this PR. I think the post id is not on the premise that permanently stored (If hexo has to store ids permanently, should use RDB). But this change may be a breaking change for some users if they are using any plugin and it depends on that premise.

---

Closes: https://github.com/hexojs/warehouse/pull/146

2023-02-06 14:11 UTC, yoshinorin commented
Hmm... We have to fix `TS2362` & `TS2322` errors before submit this PR.

2023-02-15 14:11 UTC, yoshinorin commented
I can't reproduce TS2362 & TS2322 errors locally...

2023-02-28 13:02 UTC, yoshinorin commented
Ready

2023-02-28 13:55 UTC, SukkaW requested changes
`cuid` is indeed deprecated, but I don't see any reason to upgrade to `cuid2`. `warehouse` doesn't rely on cryptographic safety

2023-03-01 20:13 UTC, SukkaW commented
> Yes. We can suspend migrating from `cuid` to `cuid2` until we really needed. (e.g. `cuid` does not work with Node.js v20) I convert this PR to draft.

Also ideally, we should consider migrating to a more performant id generation (instead of sticking with the `cuid`). `warehouse` is basically a database, and we can choose basically any random id generator we want.

Let's run a benchmark on cuid, cuid2, https://www.npmjs.com/package/uid, and https://www.npmjs.com/package/nanoid, so we can find out the fastest one.

2023-10-17 14:53 UTC, D-Sketon commented
a simple benchmark with https://github.com/ai/nanoid/blob/main/test/benchmark.js
```
cuid2                         42,848 ops/sec
nanoid                     4,442,592 ops/sec
cuid                         154,202 ops/sec

Non-secure:
uid                       65,298,000 ops/sec
```

2024-04-18 05:21 UTC, stevenjoezhang commented
Considering their performance and maintenance (update frequency), I think nanoid is a good alternative option. I will attempt to migrate to it.

2024-04-18 07:14 UTC, closed without merging