Replace typescript
hexojs/warehouse pull request #60
Opened 2019-09-26 08:17 UTC by segayuu

One of the reasons why warehouse is hardly maintained is that it doesn't understand the type.
However, the warehouse package is too complex to be typed with DefinitelyTyped, and it is quite possible to make typing errors.

2019-09-26 10:31 UTC, YoshinoriN commented
@segayuu 
IMHO we should release warehouse `v3.0` and update hexo's dependency `v3.0` before migrate to TypeScript.

2019-09-26 11:27 UTC, curbengh commented
I just added warehouse@3 as part of hexo[ v4 milestone](https://github.com/hexojs/hexo/pull/3695).

2019-09-29 14:31 UTC, YoshinoriN commented
@segayuu 
What point of view should we check? Just migrate js to ts?
For example, some instance member can specify `private`. Should we review such code?

2019-09-29 14:38 UTC, segayuu commented
The purpose of this PR is to set `noImplicityAny` to true, and strict typing from that achievement is an arbitrary position. If the `private` attribute is added, it is necessary to modify the test file implementation.

2020-11-13 15:01 UTC, YuJianghao commented
Do we have updates on this pr?

For now I think that hexo-warehouse is the best json db for tiny apps :p
Waiting for ts updates.

2020-12-31 20:06 UTC, tmirun commented
I think the same @YuJianghao

2022-06-22 06:42 UTC, yoshinorin commented
@hexojs/core 
I have been trying to migrate to TypeScript since last week.

I think maybe we can migrate it just a little bit more.
But, some tests have errors. I assume it causes by `rfdc` in `src/model.ts`.

> https://github.com/hexojs/warehouse/pull/60/files#diff-6bfea2ec3c1d21c90d6e1ecd704f380a6eeb44521e1da1a87b6a48ea691b6a43R2-R3

Dose someone would you help?

Thank you :)

2022-06-22 09:28 UTC, yoshinorin commented
@hexojs/core 
Now all tests are pass.

2022-06-22 09:30 UTC, yoshinorin commented on test/scripts/database.ts
> +// @ts-nocheck
I add `@ts-nocheck` to all test files.
This workaround is temporarily.  I will update the test code.

2022-07-23 21:33 UTC, yoshinorin commented
@hexojs/core
Now ready for review. Does someone would you please review?

I think we can improve our code more type safely and robustly. However, I think we need more time to do it. Also, I will fix if the current PR has a critical problem. But, IMHO I want to merge this PR once and improve our code step by step. 

Thank you :)

2022-07-23 21:38 UTC, yoshinorin commented on package.json
> +    "node": ">=14 <18.5"
This is a workaround.
The `Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close` error occurs with Node `18.6`. I don't know this problem is a bug or a spec change.

2022-07-23 21:41 UTC, yoshinorin commented on package.json
> +    "node": ">=14 <18.5"
IMHO we should delete `<18.5` before release the new version (`5.0.0`)

2022-08-10 10:39 UTC, yoshinorin commented on package.json
> +    "node": ">=14 <18.5"
Deleted

2022-08-10 10:43 UTC, yoshinorin commented
Updated: Merge the `master` branch to this PR branch.

2022-08-10 14:28 UTC, SukkaW requested changes

2022-08-10 14:28 UTC, SukkaW commented on src/database.ts
> +};
```suggestion
interface DatabaseOptions {
  version: number,
  path: string,
  onUpgrade: (...args: any[]) => any,
  onDowngrade: (...args: any[]) => any
}
```

Prefer `interface` when possible.

2022-08-10 14:30 UTC, SukkaW commented on src/lib/jsonstream/index.ts
> +import through2 from 'through2';
IIRC `through2` has its type definition `@types/through2`?

2022-08-11 06:56 UTC, yoshinorin commented on src/database.ts
> +};
Done :)

2022-08-11 06:57 UTC, yoshinorin commented on src/lib/jsonstream/index.ts
> +import through2 from 'through2';
Done :)

2022-09-09 01:49 UTC, renbaoshuo approved these changes

2022-10-27 02:35 UTC, stevenjoezhang approved these changes

2022-10-28 10:49 UTC, merged